apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: group-sync-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: group-sync-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
